name: meshcnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - cudatoolkit=11.3
  - matplotlib=3.5.2
  - pip=21.1.2
  - cython
  - numpy
  - pip:
    - git+https://github.com/lanpa/tensorboardX.git
    - pytest
